<a href="https://colab.research.google.com/github/manianls/ADSMI/blob/main/ADSMI_B1_M0_NB_Practice_01_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Applied Data Science and Machine Intelligence
## A program by IITM and TalentSprint
### Practice Notebook 1: Introduction to NumPy
#### (Ungraded)

## Learning Objectives

At the end of the experiment, you will be able to :

* understand the basics of NumPy including its functional objects
* describe the key characteristics of numpy arrays
* understand the difference between Python list and NumPy arrays
* use indexing to slice/select data from NumPy arrays



## Information

#### NumPy

* NumPy stands for 'Numerical Python'
* It is a package for data analysis and scientific computing with Python
* At the heart of NumPy is a basic data type, called the NumPy array. A NumPy array may have a number of dimensions, thus allowing it to represent quantities such as vectors (1D), matrices (2D), or higher dimensional arrays such as tensors.
* It offers ndarray data structure for storing and ufuncs for efficiently processing the (homogeneous) data. Some of the important functionalities include: basic slicing, advanced or fancy indexing, broadcasting, etc.

**To know more about Numpy click [here](https://numpy.org/doc/stable/user/whatisnumpy.html)**


#### Difference Between Python list and NumPy array

* Python lists are very general. They can contain any kind of object. They are dynamically typed.
* They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).

**To know more about the differece between Python list and NumPy arrays click [here](https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,contain%20elements%20of%20different%20types.)**

## Expected time to complete the experiment : 20 mins

#### Exercise 1: Import the numpy package under the name np

In [1]:
# Your code here
import numpy as np

#### Exercise 2: Create a one-dimensional array

In [2]:
# Your code here
list = [1,2,3,4]
n = np.array(list)
print(n)

[1 2 3 4]


#### Exercise 3: Create a two-dimensional array

In [4]:
# Your code here
x = np.array([[1,2,3],[3,4,5]])
print(x)

[[1 2 3]
 [3 4 5]]


#### Exercise 4: Create an array of 10 fives

In [7]:
# Your code here
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Exercise 5: Create an array of 30 zeros


In [10]:
# Your code here
array_zero=np.zeros(30)
print(array_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


#### Exercise 6: Create an array of odd integers from 20 to 40

In [24]:
 # Your code here
 list2=[range(20,40)]
 x = np.array(list2)
 print(x)
 odd = np.arange(21,40,2)
 print(odd)
 x[x%2==1]
 

[[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]
[21 23 25 27 29 31 33 35 37 39]


array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

#### Exercise 7: Create a 5 * 5 identity matrix

In [22]:
# Your code here
array_id=np.identity(5)
array_id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Exercise 8: Generate an array of 20 random numbers sampled from a standard normal distribution

In [26]:
# Your code here
rand = np.random.randn(20)
rand

array([-0.60361689,  0.19700213, -0.2957944 ,  1.43726034, -1.44696907,
        1.26845138,  0.17109995, -0.48931604,  1.04821398, -0.15568347,
        0.91258391, -1.18356056, -0.08037027, -1.32219337, -1.32914162,
       -0.37104651,  1.00002918, -0.59394797, -0.48020039,  0.39186397])

#### Exercise 9: Create a numpy array from a List

In [27]:
# Your code here
list = [1,2,3,4]
n = np.array(list)
print(n)

[1 2 3 4]


#### Exercise 10:  Create a 4 * 4 * 4 array with random values

In [42]:
# Your code here
array4=np.arange(64).reshape((4,4,4))
array4
array5=np.random.randn(64).reshape((4,4,4))
array5

array([[[-0.2398491 , -0.87443542, -1.29972648,  0.76818297],
        [-0.91613951,  0.21092105, -0.90269854,  1.16511362],
        [-1.64316372,  0.20309011,  1.66200323,  1.20385871],
        [ 1.71398168, -1.04897013,  1.80382698, -0.73963674]],

       [[-0.48199432,  0.03551878, -0.53732731,  0.18369034],
        [ 0.70173388, -2.05554084, -1.52001901,  0.14055646],
        [ 0.11084066,  0.52208838,  2.20743049,  0.52001151],
        [ 0.88445433,  0.55098315,  1.36467927, -0.0410938 ]],

       [[-0.88431263,  0.39536055,  1.36509067, -0.19873322],
        [ 0.58437717, -0.8751811 ,  0.16530931,  2.88325105],
        [ 0.34024075,  0.4092435 ,  0.4509854 , -0.02115959],
        [ 0.54430984,  0.35281783, -0.31768483, -0.61617594]],

       [[-0.29362096, -0.48109852, -0.78434165, -1.26949863],
        [-2.04390363,  0.49389533, -1.18880495,  1.68029328],
        [-0.27980267,  0.45190376,  2.03632725,  0.83336552],
        [-0.17906159, -0.72634921, -0.7207191 , -0.38493941]]])

#### Exercise 11: Create a 10 * 10 array with random values and find the minimum and maximum values 

In [47]:
# Your code here
array10=np.random.randn(100).reshape(10,10)
array10


array([[-0.22972019,  1.14645657,  0.72496491,  0.31537817,  0.20614401,
        -1.2680167 ,  0.00219229,  0.80554221,  0.8266231 ,  1.01656537],
       [ 1.07203218,  1.91374547, -0.89443787,  0.68959826,  0.73947646,
         0.15720372, -0.41602688, -0.42600124, -0.22348699,  0.90161756],
       [ 0.05586335, -0.39837287,  0.99726879, -0.53352204,  0.87983062,
        -1.42814252, -0.21567989,  0.66913702, -0.31594414, -0.29595599],
       [-0.45705715, -1.65119864, -0.62244556,  0.51506744, -0.59758072,
         0.50755065, -0.73195617,  0.00935129,  0.11476254, -1.07612697],
       [-0.66228041, -0.83508996, -1.14587104,  0.57854372, -1.73692582,
        -2.03141319,  1.12393329, -0.73568528, -1.03876183, -0.74149316],
       [ 0.43632879, -0.41367248, -0.46387626,  0.00375719,  1.02044265,
        -0.11737986,  1.43123525,  1.29038986,  0.218087  ,  0.48721564],
       [-1.01048579,  0.13438589,  0.76640524,  0.1496521 ,  1.00962071,
        -1.76453875,  0.44837835, -1.38442809

In [46]:
np.max(array10)

2.203156775048837

In [48]:
np.min(array10)

-2.0314131918136047

#### Exercise 12: Create a checkerboard 8 * 8 matrix using the tile function

In [49]:
# Your code here
np.tile([[1,0],[0,1]], (8,8))

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

#### Exercise 13: Given two arrays *A* and *B*, perform the below operations:

* A + B
* A - B
* A * B
* A / B
* A ** 3

A = np.arange(1,6)

B = np.arange(6, 15, 2)

In [52]:
# Your code here
A=np.arange(1,6)
B=np.arange(6,15,2)
A+B

array([ 7, 10, 13, 16, 19])

In [53]:
A-B

array([-5, -6, -7, -8, -9])

In [54]:
A*B

array([ 6, 16, 30, 48, 70])

In [55]:
A/B

array([0.16666667, 0.25      , 0.3       , 0.33333333, 0.35714286])

In [56]:
A**B

array([         1,        256,      59049,   16777216, 6103515625])

#### Exercise 14: Given an array *X*. Calculate sine, cosine, and tangent of *X*, element-wise.

X = np.array([1, 45, 60, 90])

In [57]:
# Your code here
X = np.array([1,45,60,90])
np.sin(x[0])

array([ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539])

In [58]:
np.cos(x)

array([[ 0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
         0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753,
         0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
        -0.90369221, -0.12796369,  0.76541405,  0.95507364,  0.26664293]])

In [59]:
np.tan(x)

array([[ 2.23716094e+00, -1.52749853e+00,  8.85165604e-03,
         1.58815308e+00, -2.13489670e+00, -1.33526407e-01,
         1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
         8.87142844e-01, -6.40533120e+00, -4.41695568e-01,
         6.61006041e-01, -7.53130148e+01, -6.23498963e-01,
         4.73814720e-01,  7.75047091e+00, -8.40771255e-01,
         3.10309661e-01,  3.61455441e+00]])

#### Exercise 15: Given an array *X*. Convert angles from degrees to radians.

X = np.array([-180.,  -90.,   90.,  180.])

In [61]:
# Your code here
X=np.array([-180., -90., 90., 180.])
np.deg2rad(X)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

#### Exercise 16: Given an array *X*. Calculate the round, ceil, floor of *X*, element-wise

X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

In [ ]:
# Your code here
X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])


In [62]:
np.round(X)

array([-180.,  -90.,   90.,  180.])

In [63]:
np.ceil(X)

array([-180.,  -90.,   90.,  180.])

In [64]:
np.floor(X)

array([-180.,  -90.,   90.,  180.])

#### Exercise 17: Given two arrays *X* and *Y*. Divide *X* by *Y* element-wise using divide, true_divide, floor_divide functions.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [65]:
# Your code here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

In [66]:
np.divide(X, Y)

array([0.25, 0.4 , 0.5 ])

In [67]:
np.true_divide(X, Y)

array([0.25, 0.4 , 0.5 ])

In [68]:
np.floor_divide(X,Y)

array([0, 0, 0])

#### Exercise 18: Given two arrays *X* and *Y*. Compute $X^Y$, element-wise.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [69]:
# Your code here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

In [70]:
X ** Y
np.power(X,Y)

array([  1,  32, 729])

#### Exercise 19:  Given an array *X*. If an element of *X* is smaller than 5, replace it with 4. And if an element of *X* is bigger than 9, replace it with 8.

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [72]:
# Your code here
X = np.array([8, 4, 22, 3, 66, 12, 1, 5])
np.clip(X, 4, 8)

array([8, 4, 8, 4, 8, 8, 4, 5])

#### Exercise 20: Use the functions len(), numpy.shape() on array *X*. How do they relate to each other? And to the ndim attribute of the arrays?

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [73]:
# Your code here
X = np.array([8, 4, 22, 3, 66, 12, 1, 5])


In [74]:
len(X)

8

In [75]:
X.shape

(8,)

In [77]:
X.ndim

1

#### Exercise 21: Create a 2-D array called X, ranging from -1 to 14 using arange() with step size 0.25. Split this array row wise into 3 equal parts and print the result.

In [78]:
# Your code here
X = np.arange(-1,14,0.25).reshape(3,20)
X

array([[-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,
         1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,
         3.5 ,  3.75],
       [ 4.  ,  4.25,  4.5 ,  4.75,  5.  ,  5.25,  5.5 ,  5.75,  6.  ,
         6.25,  6.5 ,  6.75,  7.  ,  7.25,  7.5 ,  7.75,  8.  ,  8.25,
         8.5 ,  8.75],
       [ 9.  ,  9.25,  9.5 ,  9.75, 10.  , 10.25, 10.5 , 10.75, 11.  ,
        11.25, 11.5 , 11.75, 12.  , 12.25, 12.5 , 12.75, 13.  , 13.25,
        13.5 , 13.75]])

#### Exercise 22: Use the array X created above and write the commands for the following: 

* Find the sum of all elements
* Find the sum of all elements row wise
* Find the sum of all elements column wise
* Find the max of all elements
* Find the min of all elements in each row
* Find the mean of all elements in each row
* Find the standard deviation column wise

In [ ]:
# Your code here

In [80]:
print("sum is",np.sum(X))
print("\nsum of all elements row wise\n",np.sum(X, axis=0))
print("\nsum of all elements col wise\n",np.sum(X, axis=1))
print("\nmax and min",X.max(), X.min())
print("\n min row wise",np.min(X, axis=0))
print("\n mean row wise",np.mean(X, axis=0))
print("\n standard deviation column wise",np.std(X, axis=1))

sum is 382.5

sum of all elements row wise
 [12.   12.75 13.5  14.25 15.   15.75 16.5  17.25 18.   18.75 19.5  20.25
 21.   21.75 22.5  23.25 24.   24.75 25.5  26.25]

sum of all elements col wise
 [ 27.5 127.5 227.5]

max and min 13.75 -1.0

 min row wise [-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.    1.25  1.5   1.75
  2.    2.25  2.5   2.75  3.    3.25  3.5   3.75]

 mean row wise [4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25
 7.5  7.75 8.   8.25 8.5  8.75]

 standard deviation column wise [1.44157032 1.44157032 1.44157032]
